"""empty message

Revision ID: 7f7260dddeb7
Revises: e382f8c47fff
Create Date: 2022-08-08 18:20:13.344463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f7260dddeb7'
down_revision = 'e382f8c47fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peopleFavourites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'person_id')
    )
    op.create_table('planetFavourites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'planet_id')
    )
    op.drop_index('name', table_name='favorite_person')
    op.drop_index('name_2', table_name='favorite_person')
    op.drop_index('url', table_name='favorite_person')
    op.drop_index('url_2', table_name='favorite_person')
    op.drop_table('favorite_person')
    op.drop_index('name', table_name='favorite_planet')
    op.drop_index('name_2', table_name='favorite_planet')
    op.drop_index('url', table_name='favorite_planet')
    op.drop_index('url_2', table_name='favorite_planet')
    op.drop_table('favorite_planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_planet',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=80), nullable=False),
    sa.ForeignKeyConstraint(['name'], ['planet.name'], name='favorite_planet_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_planet_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('url_2', 'favorite_planet', ['url'], unique=False)
    op.create_index('url', 'favorite_planet', ['url'], unique=False)
    op.create_index('name_2', 'favorite_planet', ['name'], unique=False)
    op.create_index('name', 'favorite_planet', ['name'], unique=False)
    op.create_table('favorite_person',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=80), nullable=False),
    sa.ForeignKeyConstraint(['name'], ['person.name'], name='favorite_person_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_person_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('url_2', 'favorite_person', ['url'], unique=False)
    op.create_index('url', 'favorite_person', ['url'], unique=False)
    op.create_index('name_2', 'favorite_person', ['name'], unique=False)
    op.create_index('name', 'favorite_person', ['name'], unique=False)
    op.drop_table('planetFavourites')
    op.drop_table('peopleFavourites')
    # ### end Alembic commands ###
