"""empty message

Revision ID: e382f8c47fff
Revises: 26a89cbf46e4
Create Date: 2022-08-08 16:11:24.157572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e382f8c47fff'
down_revision = '26a89cbf46e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favorite_person', 'person', ['name'], ['name'])
    op.create_foreign_key(None, 'favorite_planet', 'planet', ['name'], ['name'])
    op.add_column('user', sa.Column('firstName', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('lastName', sa.String(length=30), nullable=False))
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', mysql.VARCHAR(length=30), nullable=False))
    op.add_column('user', sa.Column('first_name', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'firstName')
    op.drop_constraint(None, 'favorite_planet', type_='foreignkey')
    op.drop_constraint(None, 'favorite_person', type_='foreignkey')
    # ### end Alembic commands ###
